# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lumenora
description: A plug-and-play Hyprland distro based on Wayblue and ML4W
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/llamatron/bazaar/repo/fedora-44/llamatron-bazaar-fedora-44.repo
      - https://copr.fedorainfracloud.org/coprs/chronoscrat/oh-my-posh/repo/fedora-44/chronoscrat-oh-my-posh-fedora-44.repo
    install:
      - fastfetch
      - hyprpaper
      - swww
      - bazaar-store
      - distrobox
      - mangohud
      - gamemode
      - quickshell
      - SwayNotificationCenter
      - oh-my-posh

  - type: files
    files:
      - etc: /etc

  - type: script
    scripts:
      - rebrand.sh
